#!/bin/bash

# addsite - add a new Joomla site to DDEV
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history
# 1.0 Initial version

# Variables 

# version
VERSION=1.0
# name of this
MYNAME=$(basename ${0})

# root folder for websites
SITEROOT=${HOME}/Development/Ddev

# show message function
showmessage() {
    if [ "${SILENT}" == "no" ]; then
        echo -e "$1"
    fi
}

# display usage information
usage() {
    echo -e "${MYNAME} ${VERSION}, written by René Kreijveld.\n"
    echo -e "Usage: ${MYNAME} -n <sitename> [-p <php_version>] [-j] [-s] [-h]\n"
    echo "-n the website name for the new website (without spaces)."
    echo "-p the PHP version for the new website (optional, default: 8.4)."
    echo "-j download and install Joomla (optional)."
    echo "-s silent, no messages will be shown (optional)."
    echo -e "-h display this help (optional).\n"
    exit 0
}

# Function to check if the site name contains spaces
contains_spaces() {
    if [[ "$1" =~ \  ]]; then
        return 0
    else
        return 1
    fi
}

# Parse command line arguments
SILENT="no"
JOOMLA="no"
PHP_VERSION="8.4"
while getopts "n:p:ijsh" opt; do
    case ${opt} in
    n)
        WEBSITE_NAME=$OPTARG
        ;;
    p)
        PHP_VERSION=$OPTARG
        ;;
    i)
        IGNOREFOLDER="yes"
        ;;
    j)
        JOOMLA="yes"
        ;;
    s)
        SILENT="yes"
        ;;
    h)
        usage
        ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
        usage
        ;;
    :)
        echo "Option -$OPTARG requires an argument." >&2
        usage
        ;;
    esac
done

showmessage "${MYNAME} ${VERSION}"

# check if mandatory parameters are provided
if [ -z "${WEBSITE_NAME}" ]; then
    echo "Error: website name missing."
    echo "Use ${MYNAME} -h to display help."
    exit 1
fi


# check if the site name contains spaces
if contains_spaces "${WEBSITE_NAME}"; then
    echo "Error: Site name '${WEBSITE_NAME}' contains spaces."
    echo "Use ${MYNAME} -h to display help."
    exit 1
fi

showmessage "Add new website ${WEBSITE_NAME} to DDEV."

# Set website root folder
SITE_FOLDER=${SITEROOT}/${WEBSITE_NAME}

# Ask for confirmation before proceeding
echo -e "Ready to set up website '${WEBSITE_NAME}' with PHP ${PHP_VERSION} in ${SITE_FOLDER}."
read -r -p "Do you want to continue? [Y/n] " CONFIRM
if [[ ! "${CONFIRM}" =~ ^[Yy]?$ ]]; then
    echo "Aborted."
    exit 0
fi

# Create the website directory and optionally add an index.php
if [ -d "${SITE_FOLDER}" ]; then
    showmessage "Website folder ${SITE_FOLDER} already exists, using existing folder."
else
    showmessage "Create website root folder ${SITE_FOLDER}."
    mkdir -p "${SITE_FOLDER}"
fi

cd "${SITE_FOLDER}"

# Download and unzip Joomla if needed
if [ "${JOOMLA}" == "yes" ]; then
    showmessage "Downloading and extracting latest Joomla"
    latestjoomla -s
else
    echo "<!DOCTYPE html><html><head><title>Empty DDEV php ${PHP_VERSION} website</title></head><body><h1>This is an empty DDEV website running on PHP version ${PHP_VERSION}</h1></body></html>" > index.php
    chmod 644 index.php
fi

# Create DDEV config
showmessage "Creating DDEV config"
ddev config --project-type=joomla --php-version="${PHP_VERSION}" --upload-dirs=images

# Add joomla.ini
echo "display_errors = off" > .ddev/php/joomla.ini
echo "output_buffering = off" >> .ddev/php/joomla.ini

if [ "${JOOMLA}" == "yes" ]; then
    showmessage "Adding Adminer to the project"
    ddev add-on get ddev/ddev-adminer
fi

# Start DDEV
showmessage "Starting DDEV project"
ddev start

# Run Joomla installer if needed
if [ "${JOOMLA}" == "yes" ]; then
    showmessage "Run Joomla installer"
    DB_PREFIX=$(cat /dev/urandom | LC_ALL=C tr -dc 'a-z' | head -c 5)
    ddev php installation/joomla.php install --site-name="Joomla" --admin-user="Administrator" --admin-username=admin --admin-password=AdminAdmin1! --admin-email=admin@example.com --db-type=mysqli --db-encryption=0 --db-host=db --db-user=db --db-pass="db" --db-name=db --db-prefix=${DB_PREFIX}_ --public-folder=""
    showmessage "Joomla config set sef_rewrite to true"
    ddev php cli/joomla.php config:set sef_rewrite=true
    showmessage "Joomla config set session lifetime to 120 minutes"
    ddev php cli/joomla.php config:set lifetime=120

    echo -e "Your Joomla website is ready.\n"
    echo -e "The website URL is https://${WEBSITE_NAME}.ddev.site"
    echo -e "Administrator URL is https://${WEBSITE_NAME}.ddev.site/administrator"
    echo -e "Admin username is admin"
    echo -e "Admin password is AdminAdmin1!\n"
fi

ddev describe
echo -e "Launch your website with the command: ddev launch"
