#!/bin/bash

# jdbdump -- Dump a Joomla database to SQL file.
# Supports Joomla versions running on DDEV
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history:
# 1.0 Initial version
# 1.1 Added -v verbose option
# 1.3 Added check if users starts jdbdump in a DDEV project directory
# 1.4 Add project name to dump filename if not specified in config
# 1.5 Added option to store database dump in backupfolder

VERSION=1.5

# Name of this script
MYNAME=$(basename "$0")

# Get DDEV Joomla configuration from ~/.config/ddevjoomla/config
CONFIG_DIR="${HOME}/.config/ddevjoomla"
CONFIG_FILE="${CONFIG_DIR}/config"

# Load configuration file defaults
if [[ -f "${CONFIG_FILE}" ]]; then
    source "${CONFIG_FILE}"
else
    echo "Error: configuration file ${CONFIG_FILE} not found, exiting."
    exit 1
fi

# Function to show messages (honoring silent mode)
showmessage() {
    if [[ "${SILENT}" == "no" ]]; then
        echo -e "$1"
    fi
}

# Display usage information
usage() {
    echo -e "${MYNAME} ${VERSION}, written by René Kreijveld.\n"
    echo -e "Usage: ${MYNAME} [-b] [-t] [-n] [-o] [-v] [-s] [-h]\n"
    echo "-b Store the backup in the backup folder."
    echo "-t Add a date-time-stamp to the database dump filename."
    echo "-n Do not compress the database dump with gzip."
    echo "-o Overwrite existing database dump."
    echo "-v Verbose, show all ddev output (optional)."
    echo "-s Silent mode, no messages will be shown."
    echo -e "-h Help. Display this info.\n"
    exit 0
}

# Process the arguments
SILENT="no"
USEBACKUPFOLDER="no"
COMPRESS=""
SHOWDATE="no"
OVERWRITE="no"
VERBOSE="no"
while getopts "btnovsh" opt; do
    case "${opt}" in
    b)
        USEBACKUPFOLDER="yes"
        ;;
    t)
        SHOWDATE="yes"
        ;;
    n)
        COMPRESS="--gzip=false"
        ;;
    o)
        OVERWRITE="yes"
        ;;
    v)
        VERBOSE="yes"
        ;;
    s)
        SILENT="yes"
        ;;
    h)
        usage
        ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2;
        exit 1
        ;;
    esac
done

showmessage "${MYNAME} ${VERSION}"

# Check if .ddev directory file exists
if [ ! -d ".ddev" ]; then
    echo "Error: this directory is not a DDEV project, are you at the root of the website?" >&2
    exit 1
fi

WEBSITE_NAME=$(basename "$PWD")

# Add a timestamp if requested
if [[ "${SHOWDATE}" == "yes" ]]; then
    NOW=$(date +".%Y%m%d-%H%M%S")
else
    NOW=""
fi

# Check for compression
if [[ "${COMPRESS}" == "" ]]; then
    EXTENSION=".gz"
else
    EXTENSION=""
fi

# Check if the database dump must be stored in the backupfolder.
# If not, the backupfile is stored in the root folder of the project
if [[ "${USEBACKUPFOLDER}" == "yes" ]]; then
    OUTFOLDER="${BACKUPFOLDER}/"
else
    OUTFOLDER=""
fi

# Determine output filename
if [[ -n "${DUMPFILE}" ]]; then
    OUTFILE="${OUTFOLDER}${DUMPFILE}"
else
    OUTFILE="${OUTFOLDER}${WEBSITE_NAME}-db${NOW}.sql${EXTENSION}"
fi

# Check if database dump exists
if [[ -e "${OUTFILE}" ]]; then
    if [[ "${OVERWRITE}" == "no" ]]; then
        read -r -p "Database dump ${OUTFILE} already exists. Do you want to continue? [Y/n] " CONFIRM
        if [[ ! "${CONFIRM}" =~ ^[Yy]?$ ]]; then
            echo "Aborted."
            exit 0
        fi
    else
        showmessage "Overwriting existing dump file..."
    fi
    rm -f "${OUTFILE}" 2>/dev/null
fi

showmessage "Starting database dump."

# Redirect ddev output based on -v flag
if [ "${VERBOSE}" == "yes" ]; then
    CMD_OUTPUT=/dev/stdout
else
    CMD_OUTPUT=/dev/null
fi

# Create database dump
ddev export-db ${COMPRESS} --file="${OUTFILE}" >"${CMD_OUTPUT}" 2>&1

if [[ $? -ne 0 ]]; then
    echo "Error: database dump failed." >&2
    exit 1
fi

showmessage "Database dump is ready in ${OUTFILE}."