#!/bin/bash

# jxdb -- Show and set the status of xdebug
#
# Written by René Kreijveld - email@renekreijveld.nl
# This script is free software; you may redistribute it and/or modify it.
# This script comes without any warranty. Use it at your own risk.
#
# Version history:
# 1.0 Initial version
# 1.1 Added check to test if jxdb is run at the root of a project
# 1.2 Changed check to test if a configuration.php is present

# shellcheck disable=SC2034
VERSION=1.2

# Check if .ddev directory exists
if [ ! -f "configuration.php" ]; then
    echo -e "Error: this directory is not a Joomla project, are you at the root of the website?\nUse the gosite command to go to the root of a project." >&2
    exit 1
fi

# Check command line parameter
ACTION=""
if [ $# -gt 0 ]; then
    case "$1" in
        on|ON|On)
            ACTION="on"
            ;;
        off|OFF|Off)
            ACTION="off"
            ;;
        *)
            echo "Usage: jxdb [on|off]"
            echo "  no parameter: show current xdebug status"
            echo "  on:           enable xdebug"
            echo "  off:          disable xdebug"
            exit 1
            ;;
    esac
fi

# Execute the appropriate ddev xdebug command
case "${ACTION}" in
    "")
        ddev xdebug status
        ;;
    on)
        ddev xdebug enable
        ;;
    off)
        ddev xdebug disable
        ;;
esac
